//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuocViet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANH
    {
        public string MaAnh { get; set; }
        public string MaSach { get; set; }
        public string Link { get; set; }
    
        public virtual Sach Sach { get; set; }
    }
}
